/*DROP TABLE GUEST;*/

CREATE TABLE GUEST (
    ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(70) CONSTRAINT GUEST_NAME_NULL NOT NULL,
    PHONE VARCHAR(18),
    IDCARDNUM VARCHAR(9) CONSTRAINT IDCARDNUM_NULL NOT NULL,
    BORN DATE CONSTRAINT BORN_NULL NOT NULL
);

CREATE TABLE ROOM (
    ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CAPACITY INTEGER CONSTRAINT CAPACITY_ZERO_NEGATIVE CHECK (CAPACITY > 0) CONSTRAINT CAPACITY_NULL NOT NULL,
    PRICE BIGINT CONSTRAINT PRICE_NULL NOT NULL CONSTRAINT PRICE_ZERO_NEGATIVE CHECK (PRICE > 0),
    FLOOR INTEGER CONSTRAINT FLOOR_NULL NOT NULL CONSTRAINT FLOOR_ZERO_NEGATIVE CHECK (FLOOR > 0),
    "NUMBER" VARCHAR(3) CONSTRAINT NUMBER_NULL NOT NULL,
    "TYPE" VARCHAR(9) CONSTRAINT TYPE_NULL NOT NULL
);

/*zkontrolovat spravny typ price a vseho co ma BigDecimal,
napsat podminky kontrol pro prazdne retezce atp.*/